#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/mikevader/charts/tree/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: felddy/foundryvtt
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag:

strategy:
  type: Recreate

# -- environment variables. See [image docs](https://github.com/felddy/foundryvtt-docker#environment-variables) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

  # -- Account password for foundryvtt.com. Required for downloading an application distribution.
  FOUNDRY_PASSWORD:
  # -- Account username or email address for foundryvtt.com. Required for downloading an application distribution.
  FOUNDRY_USERNAME:
  # -- S3 pre-signed URL generate from the user's profile. Required for downloading an application distribution.
  FOUNDRY_RELEASE_URL:
  # -- Admin password to be applied at startup. If omitted the admin password will be cleared. May be set using secrets.
  FOUNDRY_ADMIN_KEY:


# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 30000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
# Foundryvtt is hardcoded to use /data for its persistance for config
persistence:
  data:
    enabled: false
    emptyDir:
      enabled: false
    mountPath: /data
