remote: origin
target-branch: master
helm-extra-args: --timeout 600s
chart-dirs:
- charts/library
- charts/stable
excluded-charts:
chart-repos:
- bitnami=https://charts.bitnami.com/bitnami
- mikevader=https://mikevader.github.io/charts
- jetstack=https://charts.jetstack.io
