---
apiVersion: v2
name: error-pages
version: 1.4.18
kubeVersion: ">=1.16.0-0"
description: Server error pages in the docker image
type: application
keywords:
  - traefik
  - error-pages
home: https://github.com/mikevader/charts/tree/master/charts/stable/error-pages
sources:
  - https://github.com/tarampampam/error-pages
dependencies:
  - name: common
    repository: https://mikevader.github.io/charts
    version: 4.5.28
maintainers:
  - name: mikevader
    email: mikevader@users.noreply.github.com
icon: https://hsto.org/webt/rm/9y/ww/rm9ywwx3gjv9agwkcmllhsuyo7k.png

# renovate: image=tarampampam/error-pages
appVersion: 2.26.0

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.27
