---
apiVersion: v2
appVersion: 2.6.0
description: Server error pages in the docker image
name: error-pages
version: 1.2.2
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - error-pages
home: https://github.com/mikevader/charts/tree/master/charts/stable/error-pages
icon: https://hsto.org/webt/rm/9y/ww/rm9ywwx3gjv9agwkcmllhsuyo7k.png
sources:
  - https://github.com/tarampampam/error-pages
maintainers:
  - name: mikevader
    email: mikevader@users.noreply.github.com
dependencies:
  - name: common
    repository: https://mikevader.github.io/charts
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
