#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/mikevader/charts/tree/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: stashapp/stash
  # -- image tag
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [stashapp documentation](https://raw.githubusercontent.com/stashapp/stash/master/docker/production/docker-compose.yml)
# @default -- See below
env:
  # -- Set the container port
  STASH_PORT: 9999
  # STASH_STASH:
  # STASH_GENERATED:
  # STASH_METADATA:
  # STASH_CACHE:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 9999

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /root/.stash

  media:
    enabled: false
    mountPath: /media
