#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/mikevader/charts/tree/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/sct/overseerr
  # -- image tag
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Zurich
  # -- Set the application log level
  LOG_LEVEL: info
  S6_READ_ONLY_ROOT: '1'
  UMASK: '0022'
  UMASK_SET: '0022'

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5055

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /app/config
