---
apiVersion: v2
name: common
version: 4.5.26
kubeVersion: ">=1.16.0-0"
description: Function library for mikevader charts
type: library
keywords:
  - common
home: https://github.com/mikevader/charts/tree/master/charts/library/common
maintainers:
  - name: mikevader
    email: mikevader@users.noreply.github.com
