---
apiVersion: v2
name: firefly-iii
version: 4.1.0
kubeVersion: ">=1.16.0-0"
description: "Firefly III: a personal finances manager"
type: application
keywords:
  - firefly-iii
  - firefly
home: "https://github.com/mikevader/charts/tree/master/charts/stable/firefly-iii"
sources:
  - https://github.com/firefly-iii/firefly-iii
dependencies:
  - name: common
    repository: https://mikevader.github.io/charts
    version: 4.5.17
  - name: mariadb
    version: 13.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 12.11.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
maintainers:
  - name: mikevader
    email: mikevader@users.noreply.github.com
icon: "https://www.firefly-iii.org/assets/logo/color.png"

# renovate: image=fireflyiii/core
appVersion: version-5.6.14

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `mariadb` chart dependency to version 13.1.3
