name: "Charts: Test"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartChangesDetected:
        required: true
        type: string

jobs:
  generate-install-matrix:
    name: Generate matrix for install
    runs-on: ubuntu-latest
    outputs:
      matrix: |
        {
          "chart": ${{ steps.list-changed.outputs.charts }}
        }
      detected: ${{ steps.list-changed.outputs.detected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        if: inputs.chartChangesDetected == 'true'
        run: |
          EXCLUDED=$(yq eval -o=json '.excluded-charts // []' .github/ct-install.yaml)
          CHARTS=$(ct list-changed --config .github/ct-install.yaml)
          CHARTS_JSON=$(echo "${CHARTS}" | jq -R -s -c 'split("\n")[:-1]')
          OUTPUT_JSON=$(echo "{\"excluded\": ${EXCLUDED}, \"all\": ${CHARTS_JSON}}" | jq -c '.all-.excluded')
          echo "charts=${OUTPUT_JSON}" >> "$GITHUB_OUTPUT"
          if [[ $(echo ${OUTPUT_JSON} | jq -c '. | length') -gt 0 ]]; then
            echo "detected=true" >> "$GITHUB_OUTPUT"
          fi

  unittest:
    needs:
      - generate-install-matrix
    if: needs.generate-install-matrix.outputs.detected == 'true'
    name: Run unit tests
    strategy:
      matrix: ${{ fromJson(needs.generate-install-matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          setup-tools: |
            helmv3
          helm: "3.13.0"

      - name: Prep Helm
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run chart-testing (install)
        if: ${{ !contains(matrix.chart, 'library') }}
        run: helm unittest -f "tests/**/*_test.yaml" ${{ matrix.chart }}

      - name: Run library-chart-testing (install)
        if: ${{ contains(matrix.chart, 'library') }}
        run: |
          helm dep update helper-charts/common-test
          helm unittest -f "tests/**/*_test.yaml" helper-charts/common-test

  unittest_success:
    needs:
      - generate-install-matrix
      - unittest
    if: |
      always()
    name: Install successful
    runs-on: ubuntu-latest
    steps:
      - name: Check install matrix status
        if: ${{ (needs.generate-install-matrix.outputs.detected == 'true') && (needs.unittest.result != 'success') }}
        run: exit 1


  install-charts:
    needs:
      - unittest_success
      - generate-install-matrix
    if: needs.generate-install-matrix.outputs.detected == 'true'
    name: Install charts
    strategy:
      matrix: ${{ fromJson(needs.generate-install-matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          setup-tools: |
            helmv3
          helm: "3.13.3"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Create k3d cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.26

      - name: Remove node taints
        run: |
          kubectl taint --all=true nodes node.cloudprovider.kubernetes.io/uninitialized- || true

      - name: Run chart-testing (install)
        if: ${{ !contains(matrix.chart, 'library') }}
        run: ct install --config .github/ct-install.yaml --charts ${{ matrix.chart }}

      - name: Run library-chart-testing (install)
        if: ${{ contains(matrix.chart, 'library') }}
        run: ct install --config .github/ct-install-library.yaml --charts helper-charts/common-test

  # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  install_success:
    needs:
      - generate-install-matrix
      - install-charts
    if: |
      always()
    name: Install successful
    runs-on: ubuntu-latest
    steps:
      - name: Check install matrix status
        if: ${{ (needs.generate-install-matrix.outputs.detected == 'true') && (needs.install-charts.result != 'success') }}
        run: exit 1
