name: "Charts: Lint and test"

on:
  pull_request:
    paths:
      - '.github/workflows/charts-lint-test.yaml'
      - 'charts/**'
      - 'helper-charts/**'

jobs:
  lint:
    name: Lint charts
    runs-on: ubuntu-24.04
    outputs:
      changed: ${{ steps.list-changed.outputs.changed }}
      changed-charts: ${{ steps.list-changed.outputs.changed-charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.1

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct-lint.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "changed-charts<<EOF" >> $GITHUB_OUTPUT
            echo "$changed" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "changed-charts=" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config .github/ct-lint.yaml

  unittest:
    needs:
      - lint
    name: Run unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.1
      - name: Run tests
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v0.7.1
          cd helper-charts/common-test/
          helm dep update
          helm unittest -f "tests/**/*_test.yaml" .

  install:
    needs:
      - lint
    name: Install charts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.1

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Create k3d cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.31
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: needs.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config .github/ct-install.yaml
        if: needs.lint.outputs.changed == 'true'

      - name: Run chart-testing (install) with common chart
        run: ct install --charts helper-charts/common-test/ --config .github/ct-install-library.yaml
        if: needs.lint.outputs.changed == 'true' && (contains(needs.lint.outputs.changed-charts, 'helper-charts/common') || contains(needs.lint.outputs.changed-charts, 'charts/library') )
