name: "Charts: Update README"

on:
  workflow_call:
    inputs:
      modifiedCharts:
        required: true
        type: string
      isRenovatePR:
        required: true
        type: string
    outputs:
      commitHash:
        description: "The most recent commit hash at the end of this workflow"
        value: ${{ jobs.generate-changelog.outputs.commitHash }}

jobs:
  validate-changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check changelog annotations
        if: inputs.isRenovatePR != 'true'
        run: |
          CHARTS=(${{ inputs.modifiedCharts }})
          for i in "${CHARTS[@]}"
          do
              IFS='/' read -r -a chart_parts <<< "$i"
              ./.github/scripts/check-releasenotes.sh "charts/${chart_parts[0]}/${chart_parts[1]}"
              echo ""
          done

  generate-changelog:
    name: Generate changelog annotations
    runs-on: ubuntu-latest
    needs:
      - validate-changelog
    outputs:
      commitHash: ${{ steps.save-commit-hash.outputs.commit_hash }}
    env:
      PAT_TOKEN: ${{ secrets.K8S_AT_HOME_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.K8S_AT_HOME_TOKEN || github.token }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      # - name: Bump Chart.yaml version in test-chart
      #   if: inputs.isRenovatePR == 'true' && contains(inputs.modifiedCharts, 'common')
      #   run: |
      #     sed -i "s/^    version:.*/    version: $(grep '^version:' charts/library/common/Chart.yaml | awk '{print $2}')/" helper-charts/common-test/Chart.yaml

      # - name: Bump Chart.yaml version
      #   if: inputs.isRenovatePR == 'true' && contains(inputs.modifiedCharts, 'common')
      #   run: |
      #     sed -i "s/^version:.*/version: $(grep '^version:' charts/library/common/Chart.yaml | awk '{print $2}' | awk -F '[."]' '{$NF = $NF + 1;} 1' | sed 's/ /./g')/" charts/library/common/Chart.yaml

      # - name: Bump Chart.yaml version
      #   if: inputs.isRenovatePR == 'true'
      #   run: |
      #     CHARTS=(${{ inputs.modifiedCharts }})
      #     for i in "${CHARTS[@]}"
      #     do
      #         IFS='/' read -r -a chart_parts <<< "$i"
      #         sed -i "s/^version:.*/version: $(grep '^version:' charts/${chart_parts[0]}/${chart_parts[1]}/Chart.yaml | awk '{print $2}' | awk -F '[."]' '{$NF = $NF + 1;} 1' | sed 's/ /./g')/" charts/${chart_parts[0]}/${chart_parts[1]}/Chart.yaml
      #         echo ""
      #     done

      - name: Annotate Charts.yaml for Renovate PR's
        if: inputs.isRenovatePR == 'true' && inputs.modifiedCharts != ''
        env:
          CHECK_BRANCH: "origin/${{ github.event.repository.default_branch }}"
        run: |
          pip install -r ./.github/scripts/requirements.txt
          ./.github/scripts/renovate-releasenotes.py --check-branch "$CHECK_BRANCH" ${{ inputs.modifiedCharts }}

      - name: Create commit
        id: create-commit
        if: inputs.isRenovatePR == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: charts/**
          commit_message: "chore: Auto-update chart metadata"
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com

      # - name: Trigger workflow
      #   if: inputs.isRenovatePR == 'true' && inputs.modifiedCharts != ''
      #   run: |
      #       curl -X POST https://api.github.com/repos/mikevader/charts/actions/workflows/pr-validate/dispatches \
      #         -H 'Authorization: Bearer $PAT_TOKEN' \
      #         -H 'Accept: application/vnd.github.v3+json' \
      #         -d '{"ref":"master"}'

      - name: Save commit hash
        id: save-commit-hash
        run: |
          if [ "${{ steps.create-commit.outputs.changes_detected || 'unknown' }}" == "true" ]; then
            echo "commit_hash=${{ steps.create-commit.outputs.commit_hash }}" >> "$GITHUB_OUTPUT"
          else
            echo "commit_hash=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          fi
